version: '2'
services:
    sample1onboarding-app:
        image: sample1onboarding
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@sample1onboarding-oracle:1521:sample1Onboarding
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
